# #
# # This action will publish Chatwoot CE docker image.
# # This is set to run against merges to develop, master
# # and when tags are created.
# #

name: Publish Chatwoot CE docker images
on:
  push:
    branches:
      - develop
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }} # ref_name to get tags/branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.314ecorp.tech
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        if: github.ref_name != 'development'
        run: docker build . --file docker/Dockerfile --tag registry.314ecorp.tech/chatwoot:${{ github.ref_name }} --platform linux/amd64

      - name: Push the Docker image
        run: |
          docker push registry.314ecorp.tech/chatwoot:${{ github.ref_name }}
